version: '3.8'
services:
  web:
    build: .
    container_name: tubes1-php
    volumes:
      - .:/var/www/html
    networks:
      - app-tier
    ports:
      - 8080:80
    depends_on:
      - database

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: <insert password here>
      MYSQL_INITDB_SKIP_TZINFO: 1
    container_name: tubes1-database
    networks:
      - app-tier
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tubes1-phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PASSWORD: <insert password here>
      MYSQL_ROOT_PASSWORD: <insert password here>
    ports:
      - 8081:80
    depends_on:
      - database
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge